### ISSUE TITLE
package dependency 'fstream' missing

### ISSUE THREAD

**Issue by jonas-he** [PokemonGoers/PredictPokemon-2#79]
@bensLine @Aurel-Roci 
just make a new folder, cd into it -> run "npm install predict-pokemon" -> error because module 'fstream' was not found.

**Comment by Aurel-Roci** [comment]
@jonas-he  this is what I found about this https://github.com/npm/npm/issues/3282

**Comment by jonas-he** [comment]
@Aurel-Roci what does this mean? did the error come up for you or did it not?
I tested it on a vm of mine: installed node.js v4.0.0 (the version we are using in the docker container) and ran `npm install predict-pokemon` which gives me this:
```
$ npm install predict-pokemon
npm WARN engine node-weka@0.0.8: wanted: {"node":"~0.8.0"} (current: {"node":"4.0.0","npm":"2.14.2"})

> predict-pokemon@2.0.1 postinstall C:\Users\joniu\Desktop\Neuer Ordner\node_modules\predict-pokemon
> node scripts/postinstall.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'fstream'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\joniu\Desktop\Neuer Ordner\node_modules\predict-pokemon\scripts\postinstall.js:3:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```
So I woud suggest just putting fstream in you package.json

**Comment by Aurel-Roci** [comment]
@jonas-he I tried running `npm install predict-pokemon` on my machine and it worked.  I get no errors. I am using node `6.9.1`. So my guess is that it has to do with node version. Anyways I am gonna put it in the package dependency, it will be in a few minutes.

**Comment by jonas-he** [comment]
@Aurel-Roci thanks!
